# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_milan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_milan.MainPosition')),
            ],
        ),
    ]
