# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_milan', '0002_positionstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionstat',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
